### ISSUE TITLE
Examples/showcases on mutually dependent telescope?

### ISSUE THREAD

**Issue by ice1000** [UlfNorell/insane#1]
The two .agda files on the root directory only did something we can also do in Agda

**Comment by UlfNorell** [comment]
Can you encode a sigma as a function from bool in Agda? I have no idea whether there's some additional proof theoretic strength here (I wouldn't strongly expect so), so I'm not sure what kind of examples you are looking for.

**Comment by ice1000** [comment]
Oh I see, it seems I missed some important part. Is it the use of `f` in `If A (B (f true)) b` in `f : (b : Bool) -> If A (B (f true)) b` impossible in Agda?

**Comment by ice1000** [comment]
> I'm not sure what kind of examples you are looking for.

Actually, it's because I saw

      [x1 : A1, x2 : A2, .., xn : An] -> B

    All xi are in scope in the Ai's (and in B of course). Applications of
    insane functions must be fully applied.

in readme, but in the provided examples I don't see any `[]` with a comma inside, so it looks like there is only one pi-parameter, which looks sane. And I was saying 'is there any examples where you have pi type who has multiple parameters mutually dependent'.

**Comment by UlfNorell** [comment]
The insane part is that the type of `f` depends on the value of `f`. Having multiple mutual recursive dependencies doesn't add anything extra (you could just bundle them into one).

**Comment by ice1000** [comment]
Yeah, that's really cool! Thank you very much!

**Comment by ice1000** [comment]
Hi @UlfNorell is there any publications or related research on insanely dependent type?

**Comment by UlfNorell** [comment]
There's [Formal Objects in Type Theory Using Very Dependent Types](http://www.nuprl.org/documents/Hickey/FormalObjectsinTypeTheory.pdf), by Jason Hickey. I believe his *very dependent function space* is similar to what I have implemented here.
